// Code generated by gen_entity.go DO NOT EDIT.
// Package entity stores information about entities in Minecraft.
package entity

// ID describes the numeric ID of an entity.
type ID uint32

// Entity describes information about a type of entity.
type Entity struct {
	ID          ID
	InternalID  uint32
	DisplayName string
	Name        string
	Width       float64
	Height      float64
	Type        string
}

var (
	AcaciaBoat = Entity{
		ID:          0,
		InternalID:  0,
		DisplayName: "Acacia Boat",
		Name:        "acacia_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	AcaciaChestBoat = Entity{
		ID:          1,
		InternalID:  1,
		DisplayName: "Acacia Boat with Chest",
		Name:        "acacia_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Allay = Entity{
		ID:          2,
		InternalID:  2,
		DisplayName: "Allay",
		Name:        "allay",
		Width:       0.35,
		Height:      0.6,
		Type:        "mob",
	}
	AreaEffectCloud = Entity{
		ID:          3,
		InternalID:  3,
		DisplayName: "Area Effect Cloud",
		Name:        "area_effect_cloud",
		Width:       6,
		Height:      0.5,
		Type:        "other",
	}
	Armadillo = Entity{
		ID:          4,
		InternalID:  4,
		DisplayName: "Armadillo",
		Name:        "armadillo",
		Width:       0.7,
		Height:      0.65,
		Type:        "animal",
	}
	ArmorStand = Entity{
		ID:          5,
		InternalID:  5,
		DisplayName: "Armor Stand",
		Name:        "armor_stand",
		Width:       0.5,
		Height:      1.975,
		Type:        "living",
	}
	Arrow = Entity{
		ID:          6,
		InternalID:  6,
		DisplayName: "Arrow",
		Name:        "arrow",
		Width:       0.5,
		Height:      0.5,
		Type:        "projectile",
	}
	Axolotl = Entity{
		ID:          7,
		InternalID:  7,
		DisplayName: "Axolotl",
		Name:        "axolotl",
		Width:       0.75,
		Height:      0.42,
		Type:        "animal",
	}
	BambooChestRaft = Entity{
		ID:          8,
		InternalID:  8,
		DisplayName: "Bamboo Raft with Chest",
		Name:        "bamboo_chest_raft",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	BambooRaft = Entity{
		ID:          9,
		InternalID:  9,
		DisplayName: "Bamboo Raft",
		Name:        "bamboo_raft",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Bat = Entity{
		ID:          10,
		InternalID:  10,
		DisplayName: "Bat",
		Name:        "bat",
		Width:       0.5,
		Height:      0.9,
		Type:        "ambient",
	}
	Bee = Entity{
		ID:          11,
		InternalID:  11,
		DisplayName: "Bee",
		Name:        "bee",
		Width:       0.7,
		Height:      0.6,
		Type:        "animal",
	}
	BirchBoat = Entity{
		ID:          12,
		InternalID:  12,
		DisplayName: "Birch Boat",
		Name:        "birch_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	BirchChestBoat = Entity{
		ID:          13,
		InternalID:  13,
		DisplayName: "Birch Boat with Chest",
		Name:        "birch_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Blaze = Entity{
		ID:          14,
		InternalID:  14,
		DisplayName: "Blaze",
		Name:        "blaze",
		Width:       0.6,
		Height:      1.8,
		Type:        "hostile",
	}
	BlockDisplay = Entity{
		ID:          15,
		InternalID:  15,
		DisplayName: "Block Display",
		Name:        "block_display",
		Width:       0,
		Height:      0,
		Type:        "other",
	}
	Bogged = Entity{
		ID:          16,
		InternalID:  16,
		DisplayName: "Bogged",
		Name:        "bogged",
		Width:       0.6,
		Height:      1.99,
		Type:        "hostile",
	}
	Breeze = Entity{
		ID:          17,
		InternalID:  17,
		DisplayName: "Breeze",
		Name:        "breeze",
		Width:       0.6,
		Height:      1.77,
		Type:        "hostile",
	}
	BreezeWindCharge = Entity{
		ID:          18,
		InternalID:  18,
		DisplayName: "Wind Charge",
		Name:        "breeze_wind_charge",
		Width:       0.3125,
		Height:      0.3125,
		Type:        "projectile",
	}
	Camel = Entity{
		ID:          19,
		InternalID:  19,
		DisplayName: "Camel",
		Name:        "camel",
		Width:       1.7,
		Height:      2.375,
		Type:        "animal",
	}
	Cat = Entity{
		ID:          20,
		InternalID:  20,
		DisplayName: "Cat",
		Name:        "cat",
		Width:       0.6,
		Height:      0.7,
		Type:        "animal",
	}
	CaveSpider = Entity{
		ID:          21,
		InternalID:  21,
		DisplayName: "Cave Spider",
		Name:        "cave_spider",
		Width:       0.7,
		Height:      0.5,
		Type:        "hostile",
	}
	CherryBoat = Entity{
		ID:          22,
		InternalID:  22,
		DisplayName: "Cherry Boat",
		Name:        "cherry_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	CherryChestBoat = Entity{
		ID:          23,
		InternalID:  23,
		DisplayName: "Cherry Boat with Chest",
		Name:        "cherry_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	ChestMinecart = Entity{
		ID:          24,
		InternalID:  24,
		DisplayName: "Minecart with Chest",
		Name:        "chest_minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	Chicken = Entity{
		ID:          25,
		InternalID:  25,
		DisplayName: "Chicken",
		Name:        "chicken",
		Width:       0.4,
		Height:      0.7,
		Type:        "animal",
	}
	Cod = Entity{
		ID:          26,
		InternalID:  26,
		DisplayName: "Cod",
		Name:        "cod",
		Width:       0.5,
		Height:      0.3,
		Type:        "water_creature",
	}
	CommandBlockMinecart = Entity{
		ID:          27,
		InternalID:  27,
		DisplayName: "Minecart with Command Block",
		Name:        "command_block_minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	Cow = Entity{
		ID:          28,
		InternalID:  28,
		DisplayName: "Cow",
		Name:        "cow",
		Width:       0.9,
		Height:      1.4,
		Type:        "animal",
	}
	Creaking = Entity{
		ID:          29,
		InternalID:  29,
		DisplayName: "Creaking",
		Name:        "creaking",
		Width:       0.9,
		Height:      2.7,
		Type:        "hostile",
	}
	Creeper = Entity{
		ID:          30,
		InternalID:  30,
		DisplayName: "Creeper",
		Name:        "creeper",
		Width:       0.6,
		Height:      1.7,
		Type:        "hostile",
	}
	DarkOakBoat = Entity{
		ID:          31,
		InternalID:  31,
		DisplayName: "Dark Oak Boat",
		Name:        "dark_oak_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	DarkOakChestBoat = Entity{
		ID:          32,
		InternalID:  32,
		DisplayName: "Dark Oak Boat with Chest",
		Name:        "dark_oak_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Dolphin = Entity{
		ID:          33,
		InternalID:  33,
		DisplayName: "Dolphin",
		Name:        "dolphin",
		Width:       0.9,
		Height:      0.6,
		Type:        "passive",
	}
	Donkey = Entity{
		ID:          34,
		InternalID:  34,
		DisplayName: "Donkey",
		Name:        "donkey",
		Width:       1.3964844,
		Height:      1.5,
		Type:        "animal",
	}
	DragonFireball = Entity{
		ID:          35,
		InternalID:  35,
		DisplayName: "Dragon Fireball",
		Name:        "dragon_fireball",
		Width:       1,
		Height:      1,
		Type:        "projectile",
	}
	Drowned = Entity{
		ID:          36,
		InternalID:  36,
		DisplayName: "Drowned",
		Name:        "drowned",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	Egg = Entity{
		ID:          37,
		InternalID:  37,
		DisplayName: "Thrown Egg",
		Name:        "egg",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	ElderGuardian = Entity{
		ID:          38,
		InternalID:  38,
		DisplayName: "Elder Guardian",
		Name:        "elder_guardian",
		Width:       1.9975,
		Height:      1.9975,
		Type:        "hostile",
	}
	Enderman = Entity{
		ID:          39,
		InternalID:  39,
		DisplayName: "Enderman",
		Name:        "enderman",
		Width:       0.6,
		Height:      2.9,
		Type:        "hostile",
	}
	Endermite = Entity{
		ID:          40,
		InternalID:  40,
		DisplayName: "Endermite",
		Name:        "endermite",
		Width:       0.4,
		Height:      0.3,
		Type:        "hostile",
	}
	EnderDragon = Entity{
		ID:          41,
		InternalID:  41,
		DisplayName: "Ender Dragon",
		Name:        "ender_dragon",
		Width:       16,
		Height:      8,
		Type:        "mob",
	}
	EnderPearl = Entity{
		ID:          42,
		InternalID:  42,
		DisplayName: "Thrown Ender Pearl",
		Name:        "ender_pearl",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	EndCrystal = Entity{
		ID:          43,
		InternalID:  43,
		DisplayName: "End Crystal",
		Name:        "end_crystal",
		Width:       2,
		Height:      2,
		Type:        "other",
	}
	Evoker = Entity{
		ID:          44,
		InternalID:  44,
		DisplayName: "Evoker",
		Name:        "evoker",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	EvokerFangs = Entity{
		ID:          45,
		InternalID:  45,
		DisplayName: "Evoker Fangs",
		Name:        "evoker_fangs",
		Width:       0.5,
		Height:      0.8,
		Type:        "other",
	}
	ExperienceBottle = Entity{
		ID:          46,
		InternalID:  46,
		DisplayName: "Thrown Bottle o' Enchanting",
		Name:        "experience_bottle",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	ExperienceOrb = Entity{
		ID:          47,
		InternalID:  47,
		DisplayName: "Experience Orb",
		Name:        "experience_orb",
		Width:       0.5,
		Height:      0.5,
		Type:        "other",
	}
	EyeOfEnder = Entity{
		ID:          48,
		InternalID:  48,
		DisplayName: "Eye of Ender",
		Name:        "eye_of_ender",
		Width:       0.25,
		Height:      0.25,
		Type:        "other",
	}
	FallingBlock = Entity{
		ID:          49,
		InternalID:  49,
		DisplayName: "Falling Block",
		Name:        "falling_block",
		Width:       0.98,
		Height:      0.98,
		Type:        "other",
	}
	Fireball = Entity{
		ID:          50,
		InternalID:  50,
		DisplayName: "Fireball",
		Name:        "fireball",
		Width:       1,
		Height:      1,
		Type:        "projectile",
	}
	FireworkRocket = Entity{
		ID:          51,
		InternalID:  51,
		DisplayName: "Firework Rocket",
		Name:        "firework_rocket",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	Fox = Entity{
		ID:          52,
		InternalID:  52,
		DisplayName: "Fox",
		Name:        "fox",
		Width:       0.6,
		Height:      0.7,
		Type:        "animal",
	}
	Frog = Entity{
		ID:          53,
		InternalID:  53,
		DisplayName: "Frog",
		Name:        "frog",
		Width:       0.5,
		Height:      0.5,
		Type:        "animal",
	}
	FurnaceMinecart = Entity{
		ID:          54,
		InternalID:  54,
		DisplayName: "Minecart with Furnace",
		Name:        "furnace_minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	Ghast = Entity{
		ID:          55,
		InternalID:  55,
		DisplayName: "Ghast",
		Name:        "ghast",
		Width:       4,
		Height:      4,
		Type:        "mob",
	}
	Giant = Entity{
		ID:          56,
		InternalID:  56,
		DisplayName: "Giant",
		Name:        "giant",
		Width:       3.6,
		Height:      12,
		Type:        "hostile",
	}
	GlowItemFrame = Entity{
		ID:          57,
		InternalID:  57,
		DisplayName: "Glow Item Frame",
		Name:        "glow_item_frame",
		Width:       0.5,
		Height:      0.5,
		Type:        "other",
	}
	GlowSquid = Entity{
		ID:          58,
		InternalID:  58,
		DisplayName: "Glow Squid",
		Name:        "glow_squid",
		Width:       0.8,
		Height:      0.8,
		Type:        "passive",
	}
	Goat = Entity{
		ID:          59,
		InternalID:  59,
		DisplayName: "Goat",
		Name:        "goat",
		Width:       0.9,
		Height:      1.3,
		Type:        "animal",
	}
	Guardian = Entity{
		ID:          60,
		InternalID:  60,
		DisplayName: "Guardian",
		Name:        "guardian",
		Width:       0.85,
		Height:      0.85,
		Type:        "hostile",
	}
	Hoglin = Entity{
		ID:          61,
		InternalID:  61,
		DisplayName: "Hoglin",
		Name:        "hoglin",
		Width:       1.3964844,
		Height:      1.4,
		Type:        "animal",
	}
	HopperMinecart = Entity{
		ID:          62,
		InternalID:  62,
		DisplayName: "Minecart with Hopper",
		Name:        "hopper_minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	Horse = Entity{
		ID:          63,
		InternalID:  63,
		DisplayName: "Horse",
		Name:        "horse",
		Width:       1.3964844,
		Height:      1.6,
		Type:        "animal",
	}
	Husk = Entity{
		ID:          64,
		InternalID:  64,
		DisplayName: "Husk",
		Name:        "husk",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	Illusioner = Entity{
		ID:          65,
		InternalID:  65,
		DisplayName: "Illusioner",
		Name:        "illusioner",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	Interaction = Entity{
		ID:          66,
		InternalID:  66,
		DisplayName: "Interaction",
		Name:        "interaction",
		Width:       0,
		Height:      0,
		Type:        "other",
	}
	IronGolem = Entity{
		ID:          67,
		InternalID:  67,
		DisplayName: "Iron Golem",
		Name:        "iron_golem",
		Width:       1.4,
		Height:      2.7,
		Type:        "mob",
	}
	Item = Entity{
		ID:          68,
		InternalID:  68,
		DisplayName: "Item",
		Name:        "item",
		Width:       0.25,
		Height:      0.25,
		Type:        "other",
	}
	ItemDisplay = Entity{
		ID:          69,
		InternalID:  69,
		DisplayName: "Item Display",
		Name:        "item_display",
		Width:       0,
		Height:      0,
		Type:        "other",
	}
	ItemFrame = Entity{
		ID:          70,
		InternalID:  70,
		DisplayName: "Item Frame",
		Name:        "item_frame",
		Width:       0.5,
		Height:      0.5,
		Type:        "other",
	}
	JungleBoat = Entity{
		ID:          71,
		InternalID:  71,
		DisplayName: "Jungle Boat",
		Name:        "jungle_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	JungleChestBoat = Entity{
		ID:          72,
		InternalID:  72,
		DisplayName: "Jungle Boat with Chest",
		Name:        "jungle_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	LeashKnot = Entity{
		ID:          73,
		InternalID:  73,
		DisplayName: "Leash Knot",
		Name:        "leash_knot",
		Width:       0.375,
		Height:      0.5,
		Type:        "other",
	}
	LightningBolt = Entity{
		ID:          74,
		InternalID:  74,
		DisplayName: "Lightning Bolt",
		Name:        "lightning_bolt",
		Width:       0,
		Height:      0,
		Type:        "other",
	}
	Llama = Entity{
		ID:          75,
		InternalID:  75,
		DisplayName: "Llama",
		Name:        "llama",
		Width:       0.9,
		Height:      1.87,
		Type:        "animal",
	}
	LlamaSpit = Entity{
		ID:          76,
		InternalID:  76,
		DisplayName: "Llama Spit",
		Name:        "llama_spit",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	MagmaCube = Entity{
		ID:          77,
		InternalID:  77,
		DisplayName: "Magma Cube",
		Name:        "magma_cube",
		Width:       0.52,
		Height:      0.52,
		Type:        "mob",
	}
	MangroveBoat = Entity{
		ID:          78,
		InternalID:  78,
		DisplayName: "Mangrove Boat",
		Name:        "mangrove_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	MangroveChestBoat = Entity{
		ID:          79,
		InternalID:  79,
		DisplayName: "Mangrove Boat with Chest",
		Name:        "mangrove_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Marker = Entity{
		ID:          80,
		InternalID:  80,
		DisplayName: "Marker",
		Name:        "marker",
		Width:       0,
		Height:      0,
		Type:        "other",
	}
	Minecart = Entity{
		ID:          81,
		InternalID:  81,
		DisplayName: "Minecart",
		Name:        "minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	Mooshroom = Entity{
		ID:          82,
		InternalID:  82,
		DisplayName: "Mooshroom",
		Name:        "mooshroom",
		Width:       0.9,
		Height:      1.4,
		Type:        "animal",
	}
	Mule = Entity{
		ID:          83,
		InternalID:  83,
		DisplayName: "Mule",
		Name:        "mule",
		Width:       1.3964844,
		Height:      1.6,
		Type:        "animal",
	}
	OakBoat = Entity{
		ID:          84,
		InternalID:  84,
		DisplayName: "Oak Boat",
		Name:        "oak_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	OakChestBoat = Entity{
		ID:          85,
		InternalID:  85,
		DisplayName: "Oak Boat with Chest",
		Name:        "oak_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Ocelot = Entity{
		ID:          86,
		InternalID:  86,
		DisplayName: "Ocelot",
		Name:        "ocelot",
		Width:       0.6,
		Height:      0.7,
		Type:        "animal",
	}
	OminousItemSpawner = Entity{
		ID:          87,
		InternalID:  87,
		DisplayName: "Ominous Item Spawner",
		Name:        "ominous_item_spawner",
		Width:       0.25,
		Height:      0.25,
		Type:        "other",
	}
	Painting = Entity{
		ID:          88,
		InternalID:  88,
		DisplayName: "Painting",
		Name:        "painting",
		Width:       0.5,
		Height:      0.5,
		Type:        "other",
	}
	PaleOakBoat = Entity{
		ID:          89,
		InternalID:  89,
		DisplayName: "Pale Oak Boat",
		Name:        "pale_oak_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	PaleOakChestBoat = Entity{
		ID:          90,
		InternalID:  90,
		DisplayName: "Pale Oak Boat with Chest",
		Name:        "pale_oak_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Panda = Entity{
		ID:          91,
		InternalID:  91,
		DisplayName: "Panda",
		Name:        "panda",
		Width:       1.3,
		Height:      1.25,
		Type:        "animal",
	}
	Parrot = Entity{
		ID:          92,
		InternalID:  92,
		DisplayName: "Parrot",
		Name:        "parrot",
		Width:       0.5,
		Height:      0.9,
		Type:        "animal",
	}
	Phantom = Entity{
		ID:          93,
		InternalID:  93,
		DisplayName: "Phantom",
		Name:        "phantom",
		Width:       0.9,
		Height:      0.5,
		Type:        "mob",
	}
	Pig = Entity{
		ID:          94,
		InternalID:  94,
		DisplayName: "Pig",
		Name:        "pig",
		Width:       0.9,
		Height:      0.9,
		Type:        "animal",
	}
	Piglin = Entity{
		ID:          95,
		InternalID:  95,
		DisplayName: "Piglin",
		Name:        "piglin",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	PiglinBrute = Entity{
		ID:          96,
		InternalID:  96,
		DisplayName: "Piglin Brute",
		Name:        "piglin_brute",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	Pillager = Entity{
		ID:          97,
		InternalID:  97,
		DisplayName: "Pillager",
		Name:        "pillager",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	PolarBear = Entity{
		ID:          98,
		InternalID:  98,
		DisplayName: "Polar Bear",
		Name:        "polar_bear",
		Width:       1.4,
		Height:      1.4,
		Type:        "animal",
	}
	Potion = Entity{
		ID:          99,
		InternalID:  99,
		DisplayName: "Potion",
		Name:        "potion",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	Pufferfish = Entity{
		ID:          100,
		InternalID:  100,
		DisplayName: "Pufferfish",
		Name:        "pufferfish",
		Width:       0.7,
		Height:      0.7,
		Type:        "water_creature",
	}
	Rabbit = Entity{
		ID:          101,
		InternalID:  101,
		DisplayName: "Rabbit",
		Name:        "rabbit",
		Width:       0.4,
		Height:      0.5,
		Type:        "animal",
	}
	Ravager = Entity{
		ID:          102,
		InternalID:  102,
		DisplayName: "Ravager",
		Name:        "ravager",
		Width:       1.95,
		Height:      2.2,
		Type:        "hostile",
	}
	Salmon = Entity{
		ID:          103,
		InternalID:  103,
		DisplayName: "Salmon",
		Name:        "salmon",
		Width:       0.7,
		Height:      0.4,
		Type:        "water_creature",
	}
	Sheep = Entity{
		ID:          104,
		InternalID:  104,
		DisplayName: "Sheep",
		Name:        "sheep",
		Width:       0.9,
		Height:      1.3,
		Type:        "animal",
	}
	Shulker = Entity{
		ID:          105,
		InternalID:  105,
		DisplayName: "Shulker",
		Name:        "shulker",
		Width:       1,
		Height:      1,
		Type:        "mob",
	}
	ShulkerBullet = Entity{
		ID:          106,
		InternalID:  106,
		DisplayName: "Shulker Bullet",
		Name:        "shulker_bullet",
		Width:       0.3125,
		Height:      0.3125,
		Type:        "projectile",
	}
	Silverfish = Entity{
		ID:          107,
		InternalID:  107,
		DisplayName: "Silverfish",
		Name:        "silverfish",
		Width:       0.4,
		Height:      0.3,
		Type:        "hostile",
	}
	Skeleton = Entity{
		ID:          108,
		InternalID:  108,
		DisplayName: "Skeleton",
		Name:        "skeleton",
		Width:       0.6,
		Height:      1.99,
		Type:        "hostile",
	}
	SkeletonHorse = Entity{
		ID:          109,
		InternalID:  109,
		DisplayName: "Skeleton Horse",
		Name:        "skeleton_horse",
		Width:       1.3964844,
		Height:      1.6,
		Type:        "animal",
	}
	Slime = Entity{
		ID:          110,
		InternalID:  110,
		DisplayName: "Slime",
		Name:        "slime",
		Width:       0.52,
		Height:      0.52,
		Type:        "mob",
	}
	SmallFireball = Entity{
		ID:          111,
		InternalID:  111,
		DisplayName: "Small Fireball",
		Name:        "small_fireball",
		Width:       0.3125,
		Height:      0.3125,
		Type:        "projectile",
	}
	Sniffer = Entity{
		ID:          112,
		InternalID:  112,
		DisplayName: "Sniffer",
		Name:        "sniffer",
		Width:       1.9,
		Height:      1.75,
		Type:        "animal",
	}
	Snowball = Entity{
		ID:          113,
		InternalID:  113,
		DisplayName: "Snowball",
		Name:        "snowball",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
	SnowGolem = Entity{
		ID:          114,
		InternalID:  114,
		DisplayName: "Snow Golem",
		Name:        "snow_golem",
		Width:       0.7,
		Height:      1.9,
		Type:        "mob",
	}
	SpawnerMinecart = Entity{
		ID:          115,
		InternalID:  115,
		DisplayName: "Minecart with Monster Spawner",
		Name:        "spawner_minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	SpectralArrow = Entity{
		ID:          116,
		InternalID:  116,
		DisplayName: "Spectral Arrow",
		Name:        "spectral_arrow",
		Width:       0.5,
		Height:      0.5,
		Type:        "projectile",
	}
	Spider = Entity{
		ID:          117,
		InternalID:  117,
		DisplayName: "Spider",
		Name:        "spider",
		Width:       1.4,
		Height:      0.9,
		Type:        "hostile",
	}
	SpruceBoat = Entity{
		ID:          118,
		InternalID:  118,
		DisplayName: "Spruce Boat",
		Name:        "spruce_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	SpruceChestBoat = Entity{
		ID:          119,
		InternalID:  119,
		DisplayName: "Spruce Boat with Chest",
		Name:        "spruce_chest_boat",
		Width:       1.375,
		Height:      0.5625,
		Type:        "other",
	}
	Squid = Entity{
		ID:          120,
		InternalID:  120,
		DisplayName: "Squid",
		Name:        "squid",
		Width:       0.8,
		Height:      0.8,
		Type:        "passive",
	}
	Stray = Entity{
		ID:          121,
		InternalID:  121,
		DisplayName: "Stray",
		Name:        "stray",
		Width:       0.6,
		Height:      1.99,
		Type:        "hostile",
	}
	Strider = Entity{
		ID:          122,
		InternalID:  122,
		DisplayName: "Strider",
		Name:        "strider",
		Width:       0.9,
		Height:      1.7,
		Type:        "animal",
	}
	Tadpole = Entity{
		ID:          123,
		InternalID:  123,
		DisplayName: "Tadpole",
		Name:        "tadpole",
		Width:       0.4,
		Height:      0.3,
		Type:        "water_creature",
	}
	TextDisplay = Entity{
		ID:          124,
		InternalID:  124,
		DisplayName: "Text Display",
		Name:        "text_display",
		Width:       0,
		Height:      0,
		Type:        "other",
	}
	Tnt = Entity{
		ID:          125,
		InternalID:  125,
		DisplayName: "Primed TNT",
		Name:        "tnt",
		Width:       0.98,
		Height:      0.98,
		Type:        "other",
	}
	TntMinecart = Entity{
		ID:          126,
		InternalID:  126,
		DisplayName: "Minecart with TNT",
		Name:        "tnt_minecart",
		Width:       0.98,
		Height:      0.7,
		Type:        "other",
	}
	TraderLlama = Entity{
		ID:          127,
		InternalID:  127,
		DisplayName: "Trader Llama",
		Name:        "trader_llama",
		Width:       0.9,
		Height:      1.87,
		Type:        "animal",
	}
	Trident = Entity{
		ID:          128,
		InternalID:  128,
		DisplayName: "Trident",
		Name:        "trident",
		Width:       0.5,
		Height:      0.5,
		Type:        "projectile",
	}
	TropicalFish = Entity{
		ID:          129,
		InternalID:  129,
		DisplayName: "Tropical Fish",
		Name:        "tropical_fish",
		Width:       0.5,
		Height:      0.4,
		Type:        "water_creature",
	}
	Turtle = Entity{
		ID:          130,
		InternalID:  130,
		DisplayName: "Turtle",
		Name:        "turtle",
		Width:       1.2,
		Height:      0.4,
		Type:        "animal",
	}
	Vex = Entity{
		ID:          131,
		InternalID:  131,
		DisplayName: "Vex",
		Name:        "vex",
		Width:       0.4,
		Height:      0.8,
		Type:        "hostile",
	}
	Villager = Entity{
		ID:          132,
		InternalID:  132,
		DisplayName: "Villager",
		Name:        "villager",
		Width:       0.6,
		Height:      1.95,
		Type:        "passive",
	}
	Vindicator = Entity{
		ID:          133,
		InternalID:  133,
		DisplayName: "Vindicator",
		Name:        "vindicator",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	WanderingTrader = Entity{
		ID:          134,
		InternalID:  134,
		DisplayName: "Wandering Trader",
		Name:        "wandering_trader",
		Width:       0.6,
		Height:      1.95,
		Type:        "passive",
	}
	Warden = Entity{
		ID:          135,
		InternalID:  135,
		DisplayName: "Warden",
		Name:        "warden",
		Width:       0.9,
		Height:      2.9,
		Type:        "hostile",
	}
	WindCharge = Entity{
		ID:          136,
		InternalID:  136,
		DisplayName: "Wind Charge",
		Name:        "wind_charge",
		Width:       0.3125,
		Height:      0.3125,
		Type:        "projectile",
	}
	Witch = Entity{
		ID:          137,
		InternalID:  137,
		DisplayName: "Witch",
		Name:        "witch",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	Wither = Entity{
		ID:          138,
		InternalID:  138,
		DisplayName: "Wither",
		Name:        "wither",
		Width:       0.9,
		Height:      3.5,
		Type:        "hostile",
	}
	WitherSkeleton = Entity{
		ID:          139,
		InternalID:  139,
		DisplayName: "Wither Skeleton",
		Name:        "wither_skeleton",
		Width:       0.7,
		Height:      2.4,
		Type:        "hostile",
	}
	WitherSkull = Entity{
		ID:          140,
		InternalID:  140,
		DisplayName: "Wither Skull",
		Name:        "wither_skull",
		Width:       0.3125,
		Height:      0.3125,
		Type:        "projectile",
	}
	Wolf = Entity{
		ID:          141,
		InternalID:  141,
		DisplayName: "Wolf",
		Name:        "wolf",
		Width:       0.6,
		Height:      0.85,
		Type:        "animal",
	}
	Zoglin = Entity{
		ID:          142,
		InternalID:  142,
		DisplayName: "Zoglin",
		Name:        "zoglin",
		Width:       1.3964844,
		Height:      1.4,
		Type:        "hostile",
	}
	Zombie = Entity{
		ID:          143,
		InternalID:  143,
		DisplayName: "Zombie",
		Name:        "zombie",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	ZombieHorse = Entity{
		ID:          144,
		InternalID:  144,
		DisplayName: "Zombie Horse",
		Name:        "zombie_horse",
		Width:       1.3964844,
		Height:      1.6,
		Type:        "animal",
	}
	ZombieVillager = Entity{
		ID:          145,
		InternalID:  145,
		DisplayName: "Zombie Villager",
		Name:        "zombie_villager",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	ZombifiedPiglin = Entity{
		ID:          146,
		InternalID:  146,
		DisplayName: "Zombified Piglin",
		Name:        "zombified_piglin",
		Width:       0.6,
		Height:      1.95,
		Type:        "hostile",
	}
	Player = Entity{
		ID:          147,
		InternalID:  147,
		DisplayName: "Player",
		Name:        "player",
		Width:       0.6,
		Height:      1.8,
		Type:        "player",
	}
	FishingBobber = Entity{
		ID:          148,
		InternalID:  148,
		DisplayName: "Fishing Bobber",
		Name:        "fishing_bobber",
		Width:       0.25,
		Height:      0.25,
		Type:        "projectile",
	}
)

// ByID is an index of minecraft entities by their ID.
var ByID = map[ID]*Entity{
	0:   &AcaciaBoat,
	1:   &AcaciaChestBoat,
	2:   &Allay,
	3:   &AreaEffectCloud,
	4:   &Armadillo,
	5:   &ArmorStand,
	6:   &Arrow,
	7:   &Axolotl,
	8:   &BambooChestRaft,
	9:   &BambooRaft,
	10:  &Bat,
	11:  &Bee,
	12:  &BirchBoat,
	13:  &BirchChestBoat,
	14:  &Blaze,
	15:  &BlockDisplay,
	16:  &Bogged,
	17:  &Breeze,
	18:  &BreezeWindCharge,
	19:  &Camel,
	20:  &Cat,
	21:  &CaveSpider,
	22:  &CherryBoat,
	23:  &CherryChestBoat,
	24:  &ChestMinecart,
	25:  &Chicken,
	26:  &Cod,
	27:  &CommandBlockMinecart,
	28:  &Cow,
	29:  &Creaking,
	30:  &Creeper,
	31:  &DarkOakBoat,
	32:  &DarkOakChestBoat,
	33:  &Dolphin,
	34:  &Donkey,
	35:  &DragonFireball,
	36:  &Drowned,
	37:  &Egg,
	38:  &ElderGuardian,
	39:  &Enderman,
	40:  &Endermite,
	41:  &EnderDragon,
	42:  &EnderPearl,
	43:  &EndCrystal,
	44:  &Evoker,
	45:  &EvokerFangs,
	46:  &ExperienceBottle,
	47:  &ExperienceOrb,
	48:  &EyeOfEnder,
	49:  &FallingBlock,
	50:  &Fireball,
	51:  &FireworkRocket,
	52:  &Fox,
	53:  &Frog,
	54:  &FurnaceMinecart,
	55:  &Ghast,
	56:  &Giant,
	57:  &GlowItemFrame,
	58:  &GlowSquid,
	59:  &Goat,
	60:  &Guardian,
	61:  &Hoglin,
	62:  &HopperMinecart,
	63:  &Horse,
	64:  &Husk,
	65:  &Illusioner,
	66:  &Interaction,
	67:  &IronGolem,
	68:  &Item,
	69:  &ItemDisplay,
	70:  &ItemFrame,
	71:  &JungleBoat,
	72:  &JungleChestBoat,
	73:  &LeashKnot,
	74:  &LightningBolt,
	75:  &Llama,
	76:  &LlamaSpit,
	77:  &MagmaCube,
	78:  &MangroveBoat,
	79:  &MangroveChestBoat,
	80:  &Marker,
	81:  &Minecart,
	82:  &Mooshroom,
	83:  &Mule,
	84:  &OakBoat,
	85:  &OakChestBoat,
	86:  &Ocelot,
	87:  &OminousItemSpawner,
	88:  &Painting,
	89:  &PaleOakBoat,
	90:  &PaleOakChestBoat,
	91:  &Panda,
	92:  &Parrot,
	93:  &Phantom,
	94:  &Pig,
	95:  &Piglin,
	96:  &PiglinBrute,
	97:  &Pillager,
	98:  &PolarBear,
	99:  &Potion,
	100: &Pufferfish,
	101: &Rabbit,
	102: &Ravager,
	103: &Salmon,
	104: &Sheep,
	105: &Shulker,
	106: &ShulkerBullet,
	107: &Silverfish,
	108: &Skeleton,
	109: &SkeletonHorse,
	110: &Slime,
	111: &SmallFireball,
	112: &Sniffer,
	113: &Snowball,
	114: &SnowGolem,
	115: &SpawnerMinecart,
	116: &SpectralArrow,
	117: &Spider,
	118: &SpruceBoat,
	119: &SpruceChestBoat,
	120: &Squid,
	121: &Stray,
	122: &Strider,
	123: &Tadpole,
	124: &TextDisplay,
	125: &Tnt,
	126: &TntMinecart,
	127: &TraderLlama,
	128: &Trident,
	129: &TropicalFish,
	130: &Turtle,
	131: &Vex,
	132: &Villager,
	133: &Vindicator,
	134: &WanderingTrader,
	135: &Warden,
	136: &WindCharge,
	137: &Witch,
	138: &Wither,
	139: &WitherSkeleton,
	140: &WitherSkull,
	141: &Wolf,
	142: &Zoglin,
	143: &Zombie,
	144: &ZombieHorse,
	145: &ZombieVillager,
	146: &ZombifiedPiglin,
	147: &Player,
	148: &FishingBobber,
}
