// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var ConsumeEffectType = []string{
	"minecraft:apply_effects",
	"minecraft:remove_effects",
	"minecraft:clear_all_effects",
	"minecraft:teleport_randomly",
	"minecraft:play_sound",
}
