// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var RecipeDisplay = []string{
	"minecraft:crafting_shapeless",
	"minecraft:crafting_shaped",
	"minecraft:furnace",
	"minecraft:stonecutter",
	"minecraft:smithing",
}
