// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var RecipeBookCategory = []string{
	"minecraft:crafting_building_blocks",
	"minecraft:crafting_redstone",
	"minecraft:crafting_equipment",
	"minecraft:crafting_misc",
	"minecraft:furnace_food",
	"minecraft:furnace_blocks",
	"minecraft:furnace_misc",
	"minecraft:blast_furnace_blocks",
	"minecraft:blast_furnace_misc",
	"minecraft:smoker_food",
	"minecraft:stonecutter",
	"minecraft:smithing",
	"minecraft:campfire",
}
