// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var SlotDisplay = []string{
	"minecraft:empty",
	"minecraft:any_fuel",
	"minecraft:item",
	"minecraft:item_stack",
	"minecraft:tag",
	"minecraft:smithing_trim",
	"minecraft:with_remainder",
	"minecraft:composite",
}
