// Code generated by "stringer -type ServerboundPacketID"; DO NOT EDIT.

package packetid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerboundLoginHello-0]
	_ = x[ServerboundLoginKey-1]
	_ = x[ServerboundLoginCustomQueryAnswer-2]
	_ = x[ServerboundLoginLoginAcknowledged-3]
	_ = x[ServerboundLoginCookieResponse-4]
	_ = x[ServerboundStatusStatusRequest-0]
	_ = x[ServerboundStatusPingRequest-1]
	_ = x[ServerboundConfigClientInformation-0]
	_ = x[ServerboundConfigCookieResponse-1]
	_ = x[ServerboundConfigCustomPayload-2]
	_ = x[ServerboundConfigFinishConfiguration-3]
	_ = x[ServerboundConfigKeepAlive-4]
	_ = x[ServerboundConfigPong-5]
	_ = x[ServerboundConfigResourcePack-6]
	_ = x[ServerboundConfigSelectKnownPacks-7]
	_ = x[ServerboundAcceptTeleportation-0]
	_ = x[ServerboundBlockEntityTagQuery-1]
	_ = x[ServerboundBundleItemSelected-2]
	_ = x[ServerboundChangeDifficulty-3]
	_ = x[ServerboundChatAck-4]
	_ = x[ServerboundChatCommand-5]
	_ = x[ServerboundChatCommandSigned-6]
	_ = x[ServerboundChat-7]
	_ = x[ServerboundChatSessionUpdate-8]
	_ = x[ServerboundChunkBatchReceived-9]
	_ = x[ServerboundClientCommand-10]
	_ = x[ServerboundClientTickEnd-11]
	_ = x[ServerboundClientInformation-12]
	_ = x[ServerboundCommandSuggestion-13]
	_ = x[ServerboundConfigurationAcknowledged-14]
	_ = x[ServerboundContainerButtonClick-15]
	_ = x[ServerboundContainerClick-16]
	_ = x[ServerboundContainerClose-17]
	_ = x[ServerboundContainerSlotStateChanged-18]
	_ = x[ServerboundCookieResponse-19]
	_ = x[ServerboundCustomPayload-20]
	_ = x[ServerboundDebugSampleSubscription-21]
	_ = x[ServerboundEditBook-22]
	_ = x[ServerboundEntityTagQuery-23]
	_ = x[ServerboundInteract-24]
	_ = x[ServerboundJigsawGenerate-25]
	_ = x[ServerboundKeepAlive-26]
	_ = x[ServerboundLockDifficulty-27]
	_ = x[ServerboundMovePlayerPos-28]
	_ = x[ServerboundMovePlayerPosRot-29]
	_ = x[ServerboundMovePlayerRot-30]
	_ = x[ServerboundMovePlayerStatusOnly-31]
	_ = x[ServerboundMoveVehicle-32]
	_ = x[ServerboundPaddleBoat-33]
	_ = x[ServerboundPickItemFromBlock-34]
	_ = x[ServerboundPickItemFromEntity-35]
	_ = x[ServerboundPingRequest-36]
	_ = x[ServerboundPlaceRecipe-37]
	_ = x[ServerboundPlayerAbilities-38]
	_ = x[ServerboundPlayerAction-39]
	_ = x[ServerboundPlayerCommand-40]
	_ = x[ServerboundPlayerInput-41]
	_ = x[ServerboundPlayerLoaded-42]
	_ = x[ServerboundPong-43]
	_ = x[ServerboundRecipeBookChangeSettings-44]
	_ = x[ServerboundRecipeBookSeenRecipe-45]
	_ = x[ServerboundRenameItem-46]
	_ = x[ServerboundResourcePack-47]
	_ = x[ServerboundSeenAdvancements-48]
	_ = x[ServerboundSelectTrade-49]
	_ = x[ServerboundSetBeacon-50]
	_ = x[ServerboundSetCarriedItem-51]
	_ = x[ServerboundSetCommandBlock-52]
	_ = x[ServerboundSetCommandMinecart-53]
	_ = x[ServerboundSetCreativeModeSlot-54]
	_ = x[ServerboundSetJigsawBlock-55]
	_ = x[ServerboundSetStructureBlock-56]
	_ = x[ServerboundSignUpdate-57]
	_ = x[ServerboundSwing-58]
	_ = x[ServerboundTeleportToEntity-59]
	_ = x[ServerboundUseItemOn-60]
	_ = x[ServerboundUseItem-61]
}

const _ServerboundPacketID_name = "ServerboundLoginHelloServerboundLoginKeyServerboundLoginCustomQueryAnswerServerboundLoginLoginAcknowledgedServerboundLoginCookieResponseServerboundConfigPongServerboundConfigResourcePackServerboundConfigSelectKnownPacksServerboundChatSessionUpdateServerboundChunkBatchReceivedServerboundClientCommandServerboundClientTickEndServerboundClientInformationServerboundCommandSuggestionServerboundConfigurationAcknowledgedServerboundContainerButtonClickServerboundContainerClickServerboundContainerCloseServerboundContainerSlotStateChangedServerboundCookieResponseServerboundCustomPayloadServerboundDebugSampleSubscriptionServerboundEditBookServerboundEntityTagQueryServerboundInteractServerboundJigsawGenerateServerboundKeepAliveServerboundLockDifficultyServerboundMovePlayerPosServerboundMovePlayerPosRotServerboundMovePlayerRotServerboundMovePlayerStatusOnlyServerboundMoveVehicleServerboundPaddleBoatServerboundPickItemFromBlockServerboundPickItemFromEntityServerboundPingRequestServerboundPlaceRecipeServerboundPlayerAbilitiesServerboundPlayerActionServerboundPlayerCommandServerboundPlayerInputServerboundPlayerLoadedServerboundPongServerboundRecipeBookChangeSettingsServerboundRecipeBookSeenRecipeServerboundRenameItemServerboundResourcePackServerboundSeenAdvancementsServerboundSelectTradeServerboundSetBeaconServerboundSetCarriedItemServerboundSetCommandBlockServerboundSetCommandMinecartServerboundSetCreativeModeSlotServerboundSetJigsawBlockServerboundSetStructureBlockServerboundSignUpdateServerboundSwingServerboundTeleportToEntityServerboundUseItemOnServerboundUseItem"

var _ServerboundPacketID_index = [...]uint16{0, 21, 40, 73, 106, 136, 157, 186, 219, 247, 276, 300, 324, 352, 380, 416, 447, 472, 497, 533, 558, 582, 616, 635, 660, 679, 704, 724, 749, 773, 800, 824, 855, 877, 898, 926, 955, 977, 999, 1025, 1048, 1072, 1094, 1117, 1132, 1167, 1198, 1219, 1242, 1269, 1291, 1311, 1336, 1362, 1391, 1421, 1446, 1474, 1495, 1511, 1538, 1558, 1576}

func (i ServerboundPacketID) String() string {
	if i < 0 || i >= ServerboundPacketID(len(_ServerboundPacketID_index)-1) {
		return "ServerboundPacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerboundPacketID_name[_ServerboundPacketID_index[i]:_ServerboundPacketID_index[i+1]]
}
